### ISSUE TITLE
if(...).then(...).commit()  transaction make lease expire disabled

### ISSUE THREAD

**Issue by klom303** [mixer/etcd3#92] opened 2019-03-29 07:54 UTC
etcd3 Version: 0.2.11
etcd Version: 3.3.12
nodejs Version: 10.15.3
OS: Ubuntu 18.04

```js
    const lease = client.lease(10);
    await lease.put('xxx').value('x').exec();
```
1. running these code
2. close the nodejs  process window (simulate crash down)

lease is expected, it expires after 10s and key `xxx` is deleted.

but when I try do the same steps with the following code,  the key `xxx` is still there and the value is `y` .

```js
    const lease = client.lease(10);
    await lease.put('xxx').value('x').exec();
    await client.if('xxx', 'Value', '===', 'x')
    .then(lease.put('xxx').value('y'))
    .commit();
```
Did I got wrong usage or mistake to any principle?

**Comment by connor4312** [comment] 2019-03-29 18:22
Yep, this is a bug. For now, you can get around it by modifying your second example to be:

```js
await client
    .if('xxx', 'Value', '===', 'x')
    .then(client.put('xxx').value('y').lease(await least.grant())
    .commit();
```

**Comment by connor4312** [comment] 2019-07-03 19:04
Fixed in 5b72261

**Closed by connor4312** 2019-07-03 19:04 UTC
Labels: bug

**Comment by gtamas** [comment] 2020-02-27 14:20
@connor4312 

I have the latest lib code, but the problem is still there

>   const lease = this.client.lease(ttl);
>                 const res = this.client
>                     .if(key, 'Create', '==', 0)
>                     .then(this.client.put(key).value(value).lease(await lease.grant()) )
>                     .else(this.client.get(key))
>                     .commit();

This code creates the key, but does not apply the TTL. Key never gets deleted.
What am I doing wrong? Please help!

**Comment by gtamas** [comment] 2020-02-27 14:30
It works, sorry, false alarm :)
