### ISSUE TITLE
ts compling errror!~ use grpc native official d.ts

### ISSUE THREAD

**Issue by LastKing** [mixer/etcd3#103] opened 2019-07-16 10:26 UTC
```
node_modules/etcd3/lib/src/connection-pool.d.ts:16:98 - error TS2694: Namespace '"grpc"' has no exported member 'ChannelOptions'.

16     constructor(host: string, channelCredentials: grpc.ChannelCredentials, channelOptions?: grpc.ChannelOptions | undefined);
                                                                                                    ~~~~~~~~~~~~~~

node_modules/etcd3/lib/src/options.d.ts:2:10 - error TS2305: Module '"grpc"' has no exported member 'ChannelOptions'.

2 import { ChannelOptions } from 'grpc';
           ~~~~~~~~~~~~~~

node_modules/etcd3/lib/src/rpc.d.ts:15:43 - error TS2694: Namespace '"grpc"' has no exported member 'StatusMessage'.

15     on(event: 'status', fn: (status: grpc.StatusMessage) => void): this;
```

grpc official package don't have  ChannelOptions the type defined.
https://github.com/grpc/grpc-node/blob/master/packages/grpc-native-core/index.d.ts

etcd3 the package have d.ts of grpc 
https://github.com/mixer/etcd3/blob/master/src/types/grpc.d.ts

Are there any conflicts between the two declaration documents?

**Comment by LastKing** [comment] 2019-07-16 10:27
sorry  my English is very poor and more error!~!~ 
Thank you!~!~

**Comment by connor4312** [comment] 2019-07-16 16:20
This is a duplicate of https://github.com/mixer/etcd3/issues/54. For now, you can add `"skipLibCheck": true` in your tsconfig.

**Closed by connor4312** 2019-07-16 16:20 UTC
